apiVersion: v1
kind: Service
metadata:
  name: helloworld-nginx-service
  labels:
    app: nginx
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: helloworld-nginx
